---
title: "R Notebook"
output: html_notebook
---

```{r}
# install.packages("https://seurat.nygenome.org/src/contrib/ifnb.SeuratData_3.0.0.tar.gz", repos = NULL, type = "source")
# BiocManager::install("multtest")
```

```{r}
# devtools::document() ## RUN THIS https://stackoverflow.com/questions/36442136/exported-function-not-exported-correctly
```

```{r}
library(scMetaIntegrator)
library(Seurat)
library(ifnb.SeuratData)
library(MetaIntegrator)
library(multtest)
library(magrittr)
# for visualizing data
library(ggplot2)
library(EnhancedVolcano)
```

## Download data and update object to v5
```{r}
data("ifnb")
ifnb<-UpdateSeuratObject(ifnb)
ifnb = NormalizeData(ifnb)
```

## generate pseudopairs and unique sample ID
```{r}
ifnb@meta.data$pseudoDonor = rep(c(1,2,3), nrow(ifnb@meta.data)/2)[c(1:nrow(ifnb@meta.data))] ## randomly assign donor
ifnb@meta.data$pseudoDonor = paste0("pseudoDonor_",ifnb@meta.data$pseudoDonor)
ifnb@meta.data$sample = paste0(ifnb@meta.data$pseudoDonor,"_",ifnb@meta.data$stim)
```


## identify shared genes
```{r}
thresholdedGenes = thresholdGenesAcrossPairs(seuratObject = ifnb, uniqueSampleID = "sample", pairingColumn = "pseudoDonor", percentThreshold = 0.01)
```


## Run scMI
```{r}
scMI_output = run_scMI(
  seuratObject = ifnb,
  uniqueSampleID = "sample",
  pairingColumn = "pseudoDonor",
  comparisonGroupColumn = "stim",
  groupOne = "STIM",
  groupTwo = "CTRL",
  thresholdGenes = thresholdedGenes
)
```

## get overall DEGs
```{r}
table(scMI_output$effectSizeFDR < 0.05)
```


# Quick barplot of DEGs
```{r}
scMI_output$direction = ifelse(scMI_output$effectSize > 0, "positive","negative")
scMI_output$direction = ifelse(scMI_output$effectSize == 0, "0",scMI_output$direction)
scMI_output$significant = ifelse(scMI_output$effectSizeFDR < 0.05, "TRUE","FALSE")

ggplot(scMI_output, aes(x=significant, fill = direction)) +
  geom_bar() + theme_bw() + xlab("FDR < 0.05") + ylab("# of DEGs") +
  labs(fill="sign(effectSize)") + scale_fill_manual(values = c("#16317DFF", "#A40000FF"))
```


## Quick volcano plot of DEGs
```{r}
EnhancedVolcano(scMI_output,
    lab = scMI_output$gene,
    x = 'effectSize',
    y = 'effectSizeFDR',
    pCutoff = 10e-32,
    FCcutoff = 0.5,
    pointSize = 3.0,
    labSize = 6.0)
```
